/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfigurator: typeof import('./src/components/layout/AppConfigurator.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppMenu: typeof import('./src/components/layout/AppMenu.vue')['default']
    AppMenuItem: typeof import('./src/components/layout/AppMenuItem.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/components/layout/AppTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    InfoPanel: typeof import('./src/components/InfoPanel.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    PollutionChart: typeof import('./src/components/PollutionChart.vue')['default']
    PollutionMap: typeof import('./src/components/PollutionMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    YearlyPollutionChart: typeof import('./src/components/YearlyPollutionChart.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
